Burger menu
js-tasks-ru/htmlcss-20220414_roman645 pull request #20
Opened 2022-06-22 13:35 UTC by Olgao89

2022-06-22 13:36 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-06-23 18:54 UTC, GSemikozov requested changes

2022-06-23 18:54 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +.toggler {
.toggler + .menu - описаны как отдельные блоки, может их тогда и оформить как отдельные блоки? либо переписать как элементы текущего блока

2022-06-23 18:54 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger__title {
.burger-menu__title

2022-06-23 18:54 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger__list {
.burger-menu__list

2022-06-23 18:54 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +.button__open{
.burger-menu__open

2022-06-23 18:54 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +.button__open{
хотя нет, этот элемент вообще не является частью блока, надо удалить из стилей

2022-06-23 18:54 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +.button__close{
.burger-menu_close

2022-06-23 18:54 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +.menu {
либо это .burger-menu__menu, либо выносим как отдельный блок

2022-06-27 14:50 UTC, GSemikozov requested changes

2022-06-27 14:50 UTC, GSemikozov commented on 09-lection7/01-burger-menu/index.html
> +        <button class="burger-menu__button_open" id="burger-menu-open">
повторюсь - это не элемент блока .burger-menu, даже по структуре мы видим, что он снаружи) так что использовать здесь класс burger-menu__button_open не нужно, просто стандартная `button button_primary`

2022-06-27 14:50 UTC, GSemikozov commented on 09-lection7/01-burger-menu/index.html
> +                    <button class="burger-menu__button_close" id="burger-menu-close">
а это - просто burger-menu__close

2022-06-29 15:33 UTC, GSemikozov approved these changes

2022-06-29 15:34 UTC, merged