skeleton_solution
js-tasks-ru/htmlcss-20220414_roman645 pull request #7
Opened 2022-04-29 18:17 UTC by Olgao89

2022-04-29 18:17 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-04-29 19:47 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-04-29 19:49 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-04-29 20:00 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-05-02 21:23 UTC, GSemikozov requested changes

2022-05-02 21:23 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +margin-left: 24px;
чтобы не задавать такие марджины здесь и ниже в .skeleton__bottom, можно 1 раз задать паддинги на уровне .skeleton

2022-05-03 21:03 UTC, GSemikozov requested changes

2022-05-03 21:03 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__line, .skeleton__line_short, .skeleton__line_middle{
достаточно .skeleton__line

2022-05-04 11:44 UTC, Olgao89 commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__line, .skeleton__line_short, .skeleton__line_middle{
Если убрать skeleton__line_short и middle, то параметры описанные ниже не будут применены к ним, как тогда по другому?

2022-05-04 12:27 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__line, .skeleton__line_short, .skeleton__line_middle{
будут) просто модификатор всегда пишется рядом с тем блоком / элементом, который он модифицирует - `class="skeleton__line skeleton__line_short"`

2022-05-04 16:57 UTC, Olgao89 commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__line, .skeleton__line_short, .skeleton__line_middle{
Ок, поняла, исправила.

2022-05-04 19:16 UTC, GSemikozov approved these changes

2022-05-04 19:17 UTC, merged