modal_solution
js-tasks-ru/htmlcss-20220414_roman645 pull request #9
Opened 2022-05-05 13:13 UTC by Olgao89

2022-05-05 13:14 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-05-05 14:10 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-05-05 16:48 UTC, GSemikozov requested changes

2022-05-05 16:48 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +#modal-open {
#modal-open + #modal-close + #modal + p - всем этим элементам надо задать класс, id нужны только для того чтобы можно было использовать скрипт

2022-05-05 16:48 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +#modal-open {
сама кнопка открытия - не относится к блоку модалки, стилизации не должно быть в этом файле. Если хочется использовать красивую кнопку - можно взять одно из уже созданных нами

2022-05-05 16:48 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.modal__cover {
лишний элемент, стили можно сразу на .modal

2022-05-05 16:48 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +left: 581px;
а как будет на мобилке или планшете?)
лучше использовать паттерн размещения блока с абсолютом четко по середине (демонстрация - в лекции)

2022-05-05 16:48 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +padding: 33px;
не соответствует дизайну

2022-05-09 15:51 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-05-09 19:17 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-05-09 19:18 UTC, Olgao89 commented on 05-lection3/02-modal/modal.css
> +.modal__cover {
Если применять стили cover к .modal, то они будут применяться ко всем дочерним элементам без возможности передвинуть на слой ниже.

2022-05-10 20:03 UTC, GSemikozov requested changes

2022-05-10 20:03 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.modal__button_open {
эта кнопка - не часть компонента Модалка, триггером вызова модалки может быть вообще любой элемент и для нас это не важно

2022-05-10 20:03 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.modal__cover {
вместо absolute - fixed, opacity не использовать, вместо этого - фон через rgba (a - альфа-канал для задания прозрачности), и все будет хорошо

2022-05-10 20:03 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +width: 25%;
```
top: 50%
left: 50%
transform: translate(-50%, -50%)
```

это стандартный паттерн центрирования блока через absolute

2022-05-11 19:06 UTC, GSemikozov requested changes

2022-05-11 19:06 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.button_open {
это не часть модалки, это внешний элемент

2022-05-12 08:07 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-05-12 08:35 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-05-12 08:43 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-05-12 12:35 UTC, GSemikozov requested changes

2022-05-12 12:35 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.button_open {
конкретизирую - этот класс и стили лишние, их можно просто удалить отсюда)

2022-05-12 12:35 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.modal__button_close {
это не модификатор элемента .modal__button - такого элемента нет в модалке, поэтому - это скорее всего и имелся в виду сам элемент .modal__button)

2022-05-12 12:35 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +height: 35%;
опять же, на мобилке будет слишком маленькая модалка, лучше по высоте не ограничивать

2022-05-12 12:35 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +position: fixed;
не лишним будет указать координаты top: 0; left: 0

2022-05-12 13:44 UTC, GSemikozov requested changes

2022-05-12 13:44 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +width: 25%;
лучше max-width в px как в дизайне

2022-05-12 14:32 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-05-12 14:46 UTC, GSemikozov approved these changes

2022-05-12 14:46 UTC, merged